---
strategy: polling
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://raw.githubusercontent.com/loesak/trmnl_satgus/refs/heads/main/trmnl_data/satgus_position.json
polling_headers: ''
polling_body: ''
id: 115686
custom_fields:
- keyname: doesnt_matter
  name: SAT GUS Tracker
  field_type: author_bio
  description: Follow SAT GUS the Selfie Satellite as they orbit the earth!
  github_url: https://github.com/loesak/trmnl_satgus
name: SAT GUS
refresh_interval: 15
