name: Fetch TLE Data

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  fetch-tle:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install Poetry
      run: |
        python -m pip install --user pipx
        pipx install poetry
        
    - name: Install dependencies
      run: poetry install
        
    - name: Fetch TLE data
      run: poetry run python trmnl_satgus/fetch_tle.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add trmnl_data/satgus_tle.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update TLE data [skip ci]"
        git push 